name: Bug Report
description: Report a bug or unexpected behavior on the OSW Website
title: '[BUG] '
labels: ['bug']
assignees: []
body:
  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: Clear description of what's wrong
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      placeholder: What should happen...
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      placeholder: What actually happened...
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: "Chrome 120, Firefox 121, Safari 17"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      placeholder: "Desktop, iPhone 14, Android Tablet"
    validations:
      required: true

  - type: input
    id: operating_system
    attributes:
      label: Operating System
      placeholder: "Windows 11, macOS 14, Ubuntu 22.04"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Drag and drop images or paste them directly
    validations:
      required: false

  - type: textarea
    id: console_errors
    attributes:
      label: Console Errors
      description: Press F12 to open DevTools, then copy errors from Console tab
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I've searched existing issues to avoid duplicates
          required: true