name: Documentation Improvement
description: Improve or add documentation for the OSW Website project
title: '[DOCS] '
labels: ['documentation']
assignees: []
body:
  - type: input
    id: documentation_location
    attributes:
      label: Documentation Location
      description: File or section that needs improvement
      placeholder: "e.g., README.md, CONTRIBUTING.md"
    validations:
      required: true
  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What's the problem?
      options:
        - Missing info
        - Outdated info
        - Unclear
        - Incorrect
        - No examples
        - Broken links
        - Other
    validations:
      required: true
  - type: textarea
    id: current_documentation
    attributes:
      label: Current Documentation
      description: Paste the current text (if updating existing docs)
      placeholder: Current documentation text...
      render: markdown
    validations:
      required: false
  - type: textarea
    id: proposed_improvement
    attributes:
      label: Proposed Improvement
      description: Your proposed documentation
      placeholder: Improved documentation text...
      render: markdown
    validations:
      required: true
  - type: textarea
    id: why_this_matters
    attributes:
      label: Why This Matters
      description: How does this help users/contributors?
      placeholder: Explain the impact...
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I've searched existing issues to avoid duplicates
          required: true