name: Feature Request
description: Suggest a new feature or enhancement for the OSW Website
title: '[FEATURE] '
labels: ['enhancement']
assignees: []
body:
  - type: textarea
    id: problem_statement
    attributes:
      label: Problem Statement
      description: Describe the problem or limitation you're facing. What user need does this address?
      placeholder: Describe the problem you're trying to solve...
    validations:
      required: true
  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: Describe your proposed solution in detail...
    validations:
      required: true
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Who will benefit from this feature and why?
      placeholder: Explain the benefits and use cases...
    validations:
      required: true
  - type: checkboxes
    id: target_users
    attributes:
      label: Target Users
      description: Who will benefit from this feature? (check all that apply)
      options:
        - label: Event attendees
        - label: Speakers
        - label: Sponsors
        - label: Organizers
        - label: Contributors
  - type: textarea
    id: design_mockups
    attributes:
      label: Design/Mockups
      description: Attach mockups or links to similar implementations
      placeholder: Drag and drop images or paste links to similar features...
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any technical considerations, alternatives considered, or other relevant information
      placeholder: Add any other context about the feature request here...
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I've searched existing issues to avoid duplicates
          required: true
        - label: I've clearly described the problem and solution
          required: false